# Generated by Django 5.1.15 on 2026-07-04 13:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def _comments_to_events(apps, schema_editor):
    """ADR-021: carry existing Comments over as TimelineEvent(type=note), preserving their time."""
    Comment = apps.get_model("incidents", "Comment")
    TimelineEvent = apps.get_model("incidents", "TimelineEvent")
    for c in Comment.objects.all():
        TimelineEvent.objects.create(
            incident_id=c.incident_id,
            type="note",
            actor=(c.author.username if c.author_id else ""),
            body=c.body,
            occurred_at=c.created_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('incidents', '0003_oncallshift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveBigIntegerField()),
                ('body', models.TextField(blank=True, default='')),
                ('tag', models.CharField(choices=[('note', 'Note'), ('unexpected', 'Unexpected'), ('root-cause', 'Root cause'), ('contributing', 'Contributing')], default='note', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('note', 'Note'), ('system', 'System'), ('ai', 'AI triage')], default='note', max_length=8)),
                ('actor', models.CharField(blank=True, default='', max_length=128)),
                ('body', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='incidents.incident')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.RunPython(_comments_to_events, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['content_type', 'object_id'], name='incidents_a_content_b0364d_idx'),
        ),
    ]
