# Generated by Django 5.1.15 on 2026-07-04 16:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_annotation_timelineevent_delete_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_kind', models.CharField(choices=[('session', 'Session'), ('user', 'User')], max_length=8)),
                ('subject_hash', models.CharField(max_length=128)),
                ('window_from', models.DateTimeField(blank=True, null=True)),
                ('window_to', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('partner', 'Partner'), ('e2e', 'E2E'), ('manual', 'Manual')], default='manual', max_length=8)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('indeterminate', 'Indeterminate')], default='queued', max_length=16)),
                ('verdict', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['subject_kind', 'subject_hash'], name='incidents_s_subject_dbb3b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorSpan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trace_id', models.CharField(max_length=64)),
                ('span_id', models.CharField(blank=True, default='', max_length=32)),
                ('name', models.CharField(blank=True, default='', max_length=256)),
                ('service', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(blank=True, default='', max_length=32)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('ts', models.DateTimeField(blank=True, null=True)),
                ('session_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_spans', to='incidents.sessioncheck')),
            ],
            options={
                'ordering': ['ts', 'id'],
            },
        ),
    ]
