# Generated by Django 5.1.15 on 2026-07-04 16:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_sessioncheck_errorspan'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=512)),
                ('secret', models.CharField(max_length=128)),
                ('event_types', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('event_id', models.UUIDField()),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('error', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='incidents.webhooksubscription')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['event_type'], name='incidents_w_event_t_cf775a_idx'), models.Index(fields=['status'], name='incidents_w_status_0bd09c_idx')],
            },
        ),
    ]
