# Generated by Django 5.1.15 on 2026-07-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessioncheck',
            name='source',
            field=models.CharField(choices=[('partner', 'Partner'), ('e2e', 'E2E'), ('manual', 'Manual'), ('self_report', 'Self-report')], default='manual', max_length=16),
        ),
    ]
