# Generated by Django 5.1.15 on 2026-07-06 17:15

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_alter_sessioncheck_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-z0-9-]+$', 'environment must be lowercase letters, digits, or hyphens')])),
                ('content', models.TextField()),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('special', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['environment', '-created_at'], name='incidents_d_environ_452284_idx')],
            },
        ),
        migrations.CreateModel(
            name='EnvStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-z0-9-]+$', 'environment must be lowercase letters, digits, or hyphens')])),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['environment', '-created_at'], name='incidents_e_environ_04663d_idx')],
            },
        ),
    ]
