# Generated by Django 5.1.15 on 2026-07-06 23:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('incidents', '0016_rca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_object_id', models.CharField(max_length=64)),
                ('to_object_id', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('relates_to', 'relates to'), ('caused_by', 'caused by'), ('duplicate_of', 'duplicate of'), ('blocks', 'blocks')], default='relates_to', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('to_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['from_content_type', 'from_object_id'], name='reclink_from_idx'), models.Index(fields=['to_content_type', 'to_object_id'], name='reclink_to_idx')],
                'constraints': [models.UniqueConstraint(fields=('from_content_type', 'from_object_id', 'to_content_type', 'to_object_id', 'kind'), name='uniq_record_link')],
            },
        ),
    ]
