# Generated by Django 5.1.15 on 2026-07-11 16:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0017_recordlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingModeWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('highway', 'Highway'), ('race', 'Race')], default='race', max_length=8)),
                ('actor', models.CharField(max_length=128)),
                ('reason', models.CharField(blank=True, default='', max_length=512)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='triage_fault_domain',
            field=models.CharField(blank=True, choices=[('environment', 'Environment'), ('software', 'Software')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='incident',
            name='triage_responsibility',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('internal', 'Internal'), ('vendor', 'Vendor')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='incident',
            name='triage_verdict',
            field=models.CharField(blank=True, choices=[('real', 'Real'), ('false_positive', 'False positive'), ('undetermined', 'Undetermined')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='recordlink',
            name='kind',
            field=models.CharField(choices=[('relates_to', 'relates to'), ('caused_by', 'caused by'), ('duplicate_of', 'duplicate of'), ('blocks', 'blocks'), ('created_from', 'created from')], default='relates_to', max_length=16),
        ),
        migrations.CreateModel(
            name='TriageDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor', models.CharField(max_length=128)),
                ('responsibility', models.CharField(choices=[('client', 'Client'), ('internal', 'Internal'), ('vendor', 'Vendor')], max_length=16)),
                ('fault_domain', models.CharField(choices=[('environment', 'Environment'), ('software', 'Software')], max_length=16)),
                ('verdict', models.CharField(choices=[('real', 'Real'), ('false_positive', 'False positive'), ('undetermined', 'Undetermined')], max_length=16)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(default=dict)),
                ('disposition', models.CharField(choices=[('auto_resolve', 'Auto-resolve'), ('no_action', 'No action')], default='no_action', max_length=16)),
                ('mode', models.CharField(choices=[('highway', 'Highway'), ('race', 'Race')], default='highway', max_length=8)),
                ('provider', models.CharField(blank=True, default='', max_length=16)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_decisions', to='incidents.incident')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
