# Generated by Django 5.1.15 on 2026-07-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0018_operatingmodewindow_incident_triage_fault_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorspan',
            name='kind',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='triagedecision',
            name='disposition',
            field=models.CharField(choices=[('auto_resolve', 'Auto-resolve'), ('auto_escalate', 'Auto-escalate'), ('no_action', 'No action')], default='no_action', max_length=16),
        ),
    ]
