# Generated by Django 5.1.15 on 2026-07-11 17:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0019_errorspan_kind_alter_triagedecision_disposition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=64, unique=True)),
                ('client_secret_hash', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('redirect_uris', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OAuthAuthorizationCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('redirect_uri', models.CharField(max_length=512)),
                ('code_challenge', models.CharField(max_length=128)),
                ('code_challenge_method', models.CharField(default='S256', max_length=8)),
                ('scope', models.CharField(default='mcp', max_length=64)),
                ('used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='incidents.oauthclient')),
            ],
        ),
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('access_token_hash', models.CharField(max_length=64, unique=True)),
                ('refresh_token_hash', models.CharField(max_length=64, unique=True)),
                ('scope', models.CharField(default='mcp', max_length=64)),
                ('access_expires_at', models.DateTimeField()),
                ('refresh_expires_at', models.DateTimeField()),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='incidents.oauthclient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
